# Defines the tag for OBS and build script builds:
#!BuildTag: opensuse/backlogger

FROM opensuse/tumbleweed
RUN zypper -n in -y python3 git-core ImageMagick ghostscript libpango-1_0-0 libcairo2 libgdk_pixbuf-2_0-0 dejavu-fonts ghostscript-fonts-std python3-requests python3-urllib3 python3-PyYAML python3-pytest python3-Markdown python3-weasyprint && zypper clean -a
RUN sed -i '/pattern="PDF"/d' /etc/IM-*/policy.xml /etc/ImageMagick-*/policy.xml 2>/dev/null || true
