---
name: 'Backlog Limits Checker'
description: 'Produce a static webpage with an overview of your backlog'
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  config:
    description: The configuration file
    required: false
    default: 'queries.yaml'
  args:
    description: Additional arguments to the script
    required: false
    default: '--exit-code'
  folder:
    description: Output folder for HTML files
    required: false
    default: 'gh-pages'
  state:
    description: Output folder for state keeping
    required: false
    default: 'state'
  redmine_api_key:
    description: The Redmine API key
    required: true
  webhook_url:
    description: URL to a webhook to post a notification (e.g. for slack)
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
