---
name: Backlog Limits Checker Build
concurrency: preview-${{ github.ref }}
# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - "**"
jobs:
  backlogger_preview_build:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Run the action implemented in this repo
        if: github.event.action != 'closed'
        uses: ./
        with:
          config: queries.yaml

      - name: Save PR info
        run: |
          mkdir -p pr-info
          echo "${{ github.event.number }}" > pr-info/pr-number
          echo "${{ github.event.action }}" > pr-info/pr-action

      - name: Upload PR info
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: pr-info
          path: pr-info/

      - name: Upload preview artifact
        if: github.event.action != 'closed'
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: preview-artifact
          path: gh-pages/
